# Generated by Django 2.0.2 on 2018-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmid', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='atm',
            name='atmservices',
            field=models.ManyToManyField(to='atms.ATMService'),
        ),
    ]
