# Generated by Django 2.1.2 on 2018-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmid', models.CharField(max_length=32, unique=True)),
                ('accessibility', models.ManyToManyField(to='atms.Accessibility')),
            ],
            options={
                'ordering': ('atmid',),
            },
        ),
        migrations.CreateModel(
            name='ATMService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='atm',
            name='atm_services',
            field=models.ManyToManyField(to='atms.ATMService'),
        ),
    ]
